# Generated by Django 4.2.3 on 2023-07-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitycategory",
            name="activity_type",
            field=models.CharField(
                choices=[("EXPENSE", "EXPENSE"), ("INCOME", "INCOME")],
                default="EXPENSE",
                max_length=10,
            ),
        ),
    ]
