# Generated by Django 4.2.3 on 2023-07-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0002_activitycategory_activity_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitycategory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="activitycategory",
            name="updated_at",
        ),
    ]
