# Generated by Django 4.2.3 on 2023-07-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0004_activity_amount_currency_asset_amount_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="liability",
        ),
        migrations.AddField(
            model_name="activity",
            name="funding_sources",
            field=models.CharField(
                choices=[
                    ("CASH", "Tiền mặt"),
                    ("CREDIT CARD", "Thẻ tín dụng"),
                    ("SHORT-TERM DEBT", "Khoản nợ ngắn hạn"),
                    ("LONG-TERM DEBT", "Khoản nợ giải hạn"),
                ],
                default="CASH",
                max_length=50,
            ),
        ),
    ]
