# Generated by Django 4.2.3 on 2023-07-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0005_remove_activity_asset_remove_activity_liability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
